import os

OPEN_API_KEY = os.environ["OPENAI_API_KEY"]
PINECONE_INDEX_NAME = os.environ["PINECONE_INDEX_NAME"]
PINECONE_ENVIRONMENT = os.environ["PINECONE_ENVIRONMENT"]
PINECONE_API_KEY = os.environ["PINECONE_API_KEY"]

print(f"PINECONE_INDEX_NAME: {PINECONE_INDEX_NAME}  and type: {type(PINECONE_INDEX_NAME)}")
print(f"PINECONE_ENVIRONMENT: {PINECONE_INDEX_NAME}  and type: {type(PINECONE_INDEX_NAME)}")
print(f'PINECONE_API_KEY: {PINECONE_API_KEY} and type: {type(PINECONE_API_KEY)}')
print(f'OPEN_API_KEY: {OPEN_API_KEY} and type: {type(OPEN_API_KEY)}') 